# Generated by Django 2.1 on 2019-11-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable2group',
            name='key',
            field=models.CharField(default='', max_length=64, verbose_name='变量名'),
        ),
        migrations.AlterField(
            model_name='variable2group',
            name='val',
            field=models.CharField(default='', max_length=512, verbose_name='变量值'),
        ),
    ]
