# Generated by Django 2.1 on 2019-11-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20191106_1615'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='variable2group',
            table='variablegroup',
        ),
        migrations.AlterModelTable(
            name='variable2server',
            table='variablehost',
        ),
    ]
